name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: fushin/wbupowerapi
      VERSION: ${{ github.event.head_commit.id }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWD }}

    - name: Build Docker image
      run: docker build -t $DOCKER_IMAGE_NAME:$VERSION .

    - name: Push Docker image
      run: docker push $DOCKER_IMAGE_NAME:$VERSION
